name: Release

on:
  push:
    branches: [main, dev]

concurrency:
  group: release-${{ github.ref }}

permissions:
  contents: read

jobs:
  publish-prerelease:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          # Perform a full clone, required for tags
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - &uv-restore
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          save-cache: "false"
      - &setup-release-devkit
        uses: ./.github/actions/setup-release-devkit
      - run: uv run --project "$RUNNER_TEMP/release-devkit" --locked --no-dev publish-prerelease

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          # Perform a full clone, required for tags
          fetch-depth: 0
          fetch-tags: true
          # Persist credentials so that the release command can push release tags
          persist-credentials: true
      - *uv-restore
      - *setup-release-devkit
      - run: uv run --project "$RUNNER_TEMP/release-devkit" --locked --no-dev release
        env:
          GITHUB_TOKEN: ${{ github.token }}
